backend:
  name: git-gateway # Use test-repo for local, git-gateway for production
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

#Config
site_url: https://heroesjourney.com
display_url: https://heroesjourney.com
logo_url: https://boandco.studio/images/logo.svg

#Content
collections:
  - label: "Menu Navigation"
    name: "menus"
    editor:
      preview: false
    files:
      - label: "Links"
        name: "links"
        file: "_data/linklists/main.yml"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            label_singular: "Link"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title}}'
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "url", widget: "string"}
  - label: "Homepage"
    name: "homepage_collection"
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "block-hero"
        file: "_data/blocks/block-hero.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - label: "Headline"
            name: "headline"
            widget: "list"
            max: 3
            min: 1
            add_to_top: false
            summary: '{{fields.text}}'
            fields:
              - {label: "Text", name: "text", widget: "string"}
      - label: "About us"
        name: "block-about-us"
        file: "_data/blocks/block-about-us.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "text"}
          - label: "Descriptions"
            name: "descriptions"
            widget: "list"
            allow_add: true
            label_singular: "Description"
            summary: '{{fields.text}}'
            fields:
              - {label: "Text", name: "text", widget: "string"}
          - label: "Contact block"
            name: "contact_block"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Button"
                name: "cta"
                widget: "object"
                fields:
                  - {label: "Button Text", name: "text", widget: "string"}
                  - {label: "Button Link", name: "url", widget: "string"}
      - label: "Video"
        name: "block-video"
        file: "_data/blocks/block-video.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Thumbnail", name: "thumbnail", widget: "image"}
          - {label: "Vimeo Source", name: "vimeo_source", widget: "string"}
          - {label: "Vimeo Title", name: "vimeo_title", widget: "string"}
      - label: "Our approach"
        name: "block-approach"
        file: "_data/blocks/block-approach.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Slides"
            name: "slides"
            widget: "list"
            max: 3
            min: 1
            allow_add: true
            add_to_top: true
            collapsed: false
            label_singular: "Slide"
            summary: '{{fields.text}}'
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Text", name: "text", widget: "string"}
      - label: "Stories"
        name: "block-stories"
        file: "_data/blocks/block-stories.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - label: "Featured stories"
            name: "selected_stories"
            hint: "To edit stories navigate to the [Stories](/admin/#/collections/stories) tab."
            widget: "relation"
            collection: "stories"
            search_fields: ["title"]
            value_field: "title"
            display_fields: ["title"]
            multiple: true
            max: 4
      - label: "Partners"
        name: "block-partners"
        file: "_data/blocks/block-partners.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - label: "Partners"
            name: "partners"
            widget: "list"
            label_singular: "Partner"
            allow_add: true
            collapsed: true
            add_to_top: false
            summary: '{{fields.name}}'
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Learn more link", name: "url", widget: "string", required: false}
      - label: "Team"
        name: "block-team"
        file: "_data/blocks/block-team.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Team Groupings"
            name: "groups"
            widget: "list"
            label_singular: "Group"
            collapsed: true
            add_to_top: true
            summary: '{{fields.name}}'
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - label: "Members"
                name: "members"
                widget: "list"
                label_singular: "Member"
                collapsed: true
                add_to_top: true
                summary: '{{fields.name}} - {{fields.role}}'
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Role", name: "role", widget: "string"}
                  - {label: "Description", name: "description", widget: "markdown", required: false}
      - label: "Keystones"
        name: "block-keystones"
        file: "_data/blocks/block-keystones.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Subtitle", name: "sticky_subtitle", widget: "string"}
          - label: "Keystones"
            name: "keystones" 
            widget: "list"
            label_singular: "Value"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title.title}}'
            field: {label: "Keystone", name: "title", widget: "string"}
          - {label: "Keystone Journey Map", name: "journey_map_source", widget: "file"}
      - label: "CM Summit"
        name: "block-summit"
        file: "_data/blocks/block-summit.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
      - label: "Quotes"
        name: "block-quote"
        file: "_data/blocks/block-quote.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            hint: "Only the top 2 are displayed in order on the homepage."
            min: 2
            label_singular: "Quote"
            collapsed: true
            add_to_top: true
            summary: '{{fields.quote}} - {{fields.author}}'
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Author", name: "author", widget: "string"}
      - label: "Topics"
        name: "block-topics"
        file: "_data/blocks/block-topics.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Topics"
            name: "topics"
            widget: "list"
            label_singular: "Topic"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title}}'
            fields:
              - {label: "Title", name: "title", widget: "string"}
      - label: "Contact"
        name: "block-contact"
        file: "_data/blocks/block-contact.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Email", name: "email", widget: "string"}
  - label: "Stories"
    name: "stories"
    folder: "_stories"
    create: true
    slug: "{{slug}}"
    label_singular: "Story"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Thumbnail", name: "image", widget: "image", choose_url: true}
      - {label: "Story Video", name: "source", widget: "file"}
  - label: "Footer"
    name: "footer"
    editor:
      preview: false
    files:
      - label: "Footer Content"
        name: "content"
        file: "_data/footer.yml"
        fields:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - label: "Address"
                name: "address"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
              - {label: "Phone number", "name": "phone_number", widget: "string"}
              - {label: "Email", "name": "email", widget: "string"}
          - label: "Social Media"
            name: "socials"
            widget: "object"
            fields:
              - {label: "Show social icons", name: "show_social_media", widget: "boolean"}

                
              