backend:
  name: git-gateway # Use test-repo for local, git-gateway for production
  branch: main # Branch to update (optional; defaults to master)
  # local_backend: true

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

#Config
site_url: https://journey10x.com
display_url: https://journey10x.com
logo_url: https://boandco.studio/images/netlify-logo.png

collections:
  - label: "Homepage"
    name: "homepage_collection"
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "block-hero"
        file: "_data/blocks/block-hero.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Headline", name: "headline", widget: "string"}
      - label: "About us"
        name: "block-about-us"
        file: "_data/blocks/block-about-us.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
      - label: "Clients"
        name: "block-clients"
        file: "_data/blocks/block-clients.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - label: "Clients"
            name: "client_logos"
            widget: "list"
            allow_add: true
            label_singular: 'Client'
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Logo", name: "image", choose_url: false, widget: "image"}

  - label: "Projects"
    name: "projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display on homepage", name: "display_on_homepage", widget: "boolean", default: true}
      - {label: "Media Type (Social Media, TV/Streaming)", name: "media", widget: "string"}
      - {label: "Credit Name", name: "credit_name", widget: "string"}
      - {label: "Credit Role", name: "credit_title", widget: "string"}
      - {label: "Thumbnail", name: "image", widget: "image", choose_url: true}
      - {label: "Project Video", name: "source", widget: "file"}