backend:
  name: git-gateway # Use test-repo for local, git-gateway for production
  branch: main # Branch to update (optional; defaults to master)
  # local_backend: true

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

#Config
site_url: https://heroesjourney.com
display_url: https://heroesjourney.com
logo_url: https://boandco.studio/images/logo.svg

#Content
collections:
  - label: "Homepage"
    name: "homepage_collection"
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "block-hero"
        file: "_data/blocks/block-hero.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Headline", name: "headline", widget: "text"}
      - label: "About us"
        name: "block-about-us"
        file: "_data/blocks/block-about-us.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "text"}
      - label: "Clients"
        name: "block-clients"
        file: "_data/blocks/block-clients.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - label: "Clients"
            name: "client_logos"
            widget: "list"
            allow_add: true
            label_singular: "Client"
            summary: '{{fields.name}}'
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Logo", name: "image", choose_url: false, widget: "image"}
      - label: "Stories"
        name: "block-stories"
        file: "_data/blocks/block-stories.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Description", name: "description",  widget: "text"}
          - label: "Featured stories"
            name: "selected_stories"
            hint: "To edit stories navigate to the [Stories](/admin/#/collections/stories) tab."
            widget: "relation"
            collection: "stories"
            search_fields: ["title"]
            value_field: "title"
            display_fields: ["title"]
            multiple: true
            max: 4
      - label: "Values"
        name: "block-values"
        file: "_data/blocks/block-values.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - label: "Values"
            name: "values" 
            widget: "list"
            label_singular: "Value"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title.title}}'
            field: {label: "Value", name: "title", widget: "string"}
      - label: "Services"
        name: "block-services"
        file: "_data/blocks/block-services.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - label: "Services"
            name: "services"
            widget: "list"
            label_singular: "Service"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title}} - {{fields.description}}'
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
      - label: "Team"
        name: "block-team"
        file: "_data/blocks/block-team.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Team Members"
            name: "members"
            widget: "list"
            label_singular: "Team member"
            collapsed: true
            add_to_top: true
            summary: '{{fields.name}} - {{fields.role}}'
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
      - label: "Divider"
        name: "block-divider"
        file: "_data/blocks/block-divider.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
      - label: "Locations"
        name: "block-locations"
        file: "_data/blocks/block-locations.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - label: "Locations"
            name: "location_list"
            widget: "list"
            label_singular: "Location"
            collapsed: true
            add_to_top: true
            summary: '{{fields.airport_code}} - {{fields.name}}'
            fields:
              - {label: "Airport Code", name: "airport_code", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
      - label: "Contact"
        name: "block-contact"
        file: "_data/blocks/block-contact.yml"
        fields:
          - {label: "Template", name: "template", widget: "hidden"}
          - {label: "Section Title", name: "section_title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
  - label: "Work"
    name: "projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    label_singular: "Project"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Media Type (Social Media, TV/Streaming)", name: "media", widget: "string"}
      - {label: "Credit Name", name: "credit_name", widget: "string"}
      - {label: "Credit Role", name: "credit_title", widget: "string"}
      - {label: "Thumbnail", name: "image", widget: "image", choose_url: true}
      - {label: "Project Video", name: "source", widget: "file"}
  - label: "Footer"
    name: "footer"
    editor:
      preview: false
    files:
      - label: "Links"
        name: "links"
        file: "_data/linklists/footer.yml"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            label_singular: "Link"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title}}'
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "url", widget: "string"}
      - label: "Contact"
        name: "contact"
        file: "_data/footer/contact.yml"
        fields:
          - label: "Address Lines"
            name: "address"
            widget: "list"
            label_singular: "Address line"
            collapsed: true
            add_to_top: true
            summary: '{{fields.title.title}}'
            field: {label: "Address line", name: "title", widget: "string"}
          - {label: "Phone number", name: "phone_number", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
      - label: "Socials"
        name: "socials"
        file: "_data/footer/socials.yml"
        fields:
          - {label: "Show social media", name: "show_social_media", widget: "boolean", default: true}
          - label: "Social Links"
            name: "social_media"
            widget: "list"
            label_singular: "Link"
            collapsed: true
            add_to_top: true
            summary: '{{fields.social_network}}'
            fields:
              - {label: "Link", name: "url", widget: "string"}
              - {label: "Name", name: "social_network", widget: "string"}